branches:
  - 'main'
  - '+([0-9])?(.{+([0-9])}).x'
  - name: next
    channel: next
  - name: beta
    channel: beta
  - name: alpha
    channel: alpha
ci: true
debug: true
dryRun: false
tagFormat: 'v${version}'

# Global plugin options (will be passed to all plugins)
preset: 'conventionalcommits'

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@semantic-release/changelog"
  - "@semantic-release/git"

###
# Setup plugins:
#   https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/plugins.md
###

# Responsible for verifying conditions necessary to proceed with the release:
# configuration is correct, authentication tokens are valid, etc...
verifyConditions:
  - '@semantic-release/changelog'
  # Verify the presence and the validity of the configuration
  - '@semantic-release/git'
  # Verify the presence and the validity of the Git authentication
  # and release configuration
  - '@semantic-release/github'
  # Verify the presence and the validity of the GitLab authentication
  # and release configuration

# Responsible for determining the type of the next release (major, minor or patch).
# If multiple plugins with a analyzeCommits step are defined, the release type will be
# the highest one among plugins output.
# Look details at: https://github.com/semantic-release/commit-analyzer#configuration
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    # Determine the type of release by analyzing commits with conventional-changelog
    releaseRules:
      - breaking: true  # A breaking change still goes to the minor version until the  first 1.x release
        release: minor
      - type: feat      # A new feature
        release: minor
      - type: fix       # A bug fix
        release: patch
      - type: build     # Changes that affect the build system or external dependencies
        release: patch
      - type: chore     # Other changes that don't modify src or test files
        release: false
      - type: ci        # Changes to our CI configuration files and scripts
        release: false
      - type: docs      # Documentation only changes
        release: patch
      - type: perf      # A code change that improves performance
        release: patch
      - type: refactor  # A code change that neither fixes a bug nor adds a feature
        release: false
      - type: revert    # Reverts a previous commit
        release: patch
      - type: style     # Changes that do not affect the meaning of the code
        release: false
      - type: test      # Adding missing tests or correcting existing tests
        release: false

# Responsible for generating the content of the release notes.
# If multiple plugins with a generateNotes step are defined,
# the release notes will be the result of the concatenation of each plugin output.
generateNotes:
  - path: '@semantic-release/release-notes-generator'
    linkCompare: true
    linkReferences: true
    parserOpts:
      # detect GitHub issues in merge commits
      issuePrefixes: ['#']
      noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES']
    presetConfig:
      types:  # looks like it only works with 'conventionalcommits' preset
        - type: 'feat'
          section: 'Features'
        - type: 'fix'
          section: 'Bug Fixes'
        - type: 'chore'
          section: 'Other'
        - type: 'docs'
          section: 'Docs'
        - type: 'example'
          section: 'Examples'
        - type: 'perf'
          section: 'Performance'
        - type: 'build'
          section: 'CI/CD'
          hidden: true
        - type: 'ci'
          section: 'CI/CD'
          hidden: true
        - type: 'refactor'
          section: 'Refactor'
          hidden: true
        - type: 'revert'
          section: 'Reverts'
          hidden: true
        - type: 'style'
          section: 'Style'
          hidden: true
        - type: 'test'
          section: 'Tests'
          hidden: true

# Responsible for preparing the release, for example creating or updating files
# such as package.json, CHANGELOG.md, documentation or compiled assets
# and pushing a commit.
prepare:
  - path: '@semantic-release/changelog'
    # Create or update the changelog file in the local project repository
  - path: '@semantic-release/git'
    # Push a release commit and tag, including configurable files
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    assets: ['CHANGELOG.md']

# Responsible for publishing the release.
publish:
  - path: '@semantic-release/github'

success:
  - path: '@semantic-release/github'
    successComment: false # Don't add comments to issues and PRs included in this release
