swagger: '2.0'

info:
  title: Keptn API Models
  version: 0.1.0

definitions:
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
        description: Error code
      message:
        type: string
        description: Error message

  Version:
    type: object
    properties:
      version:
        type: string
        description: Version identifier

  CreateProject:
    type: object
    required:
      - name
      - shipyard
    properties:
      name:
        type: string
      shipyard:
        type: string
      gitUser:
        type: string
      gitToken:
        type: string
      gitRemoteURL:
        type: string

  Project:
    type: object
    properties:
      projectName:
        type: string
        description: Project name
      gitUser:
        type: string
        description: Git User
      gitRemoteURI:
        type: string
        description: Git remote URI
      gitToken:
        type: string
        description: Git token
      stages:
        type: array
        items:
          $ref: '#/definitions/Stage'

  Projects:
    type: object
    properties:
      nextPageKey:
        type: string
        description: Pointer to next page, base64 encoded
      totalCount:
        type: number
        description: Total number of projects
      pageSize:
        type: number
        description: Size of returned page
      projects:
        type: array
        items:
          $ref: '#/definitions/Project'

  Stage:
    type: object
    properties:
      stageName:
        type: string
        description: Stage name
      services:
        type: array
        items:
          $ref: '#/definitions/Service'

  Stages:
    type: object
    properties:
      nextPageKey:
        type: string
        description: Pointer to next page, base64 encoded
      totalCount:
        type: number
        description: Total number of stages
      pageSize:
        type: number
        description: Size of returned page
      stages:
        type: array
        items:
          $ref: '#/definitions/Stage'


  CreateService:
    type: object
    required:
      - serviceName
    properties:
      serviceName:
        type: string
      helmChart:
        type: string
      deploymentStrategies:
        type: object
        additionalProperties:
          type: string
  Service:
    type: object
    properties:
      serviceName:
        type: string
        description: Service name
      deployedImage:
        type: string
        description: Currently deployed image
      creationDate:
        type: string
        description: Creation date of the service
      openApprovals:
        type: array
        items:
          $ref: '#/definitions/Approval'
      lastEventTypes:
        type: object
        additionalProperties:
          $ref: '#/definitions/EventContextInfo'

  Approval:
    type: object
    properties:
      keptnContext:
        type: string
        description: Keptn Context ID of the event
      eventId:
        type: string
        description: ID of the event
      time:
        type: string
        description: Time of the event
      image:
        type: string
      tag:
        type: string

  EventContextInfo:
    type: object
    properties:
      keptnContext:
        type: string
        description: Keptn Context ID of the event
      eventId:
        type: string
        description: ID of the event
      time:
        type: string
        description: Time of the event

  Services:
    type: object
    properties:
      nextPageKey:
        type: string
        description: Pointer to next page, base64 encoded
      totalCount:
        type: number
        description: Total number of services
      pageSize:
        type: number
        description: Size of returned page
      services:
        type: array
        items:
          $ref: '#/definitions/Service'

  Resource:
    type: object
    required:
      - resourceURI
    properties:
      resourceURI:
        type: string
        description: Resource URI
      resourceContent:
        type: string
        # format: byte
        description: Resource content

  Resources:
    type: object
    properties:
      nextPageKey:
        type: string
        description: Pointer to next page, base64 encoded
      totalCount:
        type: number
        description: Total number of resources
      pageSize:
        type: number
        description: Size of returned page
      resources:
        type: array
        items:
          $ref: '#/definitions/Resource'

  EventContext:
    type: object
    required:
      - token
      - keptnContext
    properties:
      token:
        type: string
      keptnContext:
        type: string

  KeptnContextExtendedCE:
    type: object
    properties: # CloudEvents v0.2 properties (https://raw.githubusercontent.com/cloudevents/spec/v0.2/spec.json#/definitions/event)
      shkeptncontext:
        type: string
      specversion:
        type: string
      contenttype:
        type: string
      data:
        type: ["object", "string"]
      id:
        type: string
      time:
        type: string
        format: date-time
      type:
        type: string
      extensions:
        type: object
      source:
        format: uri-reference
        type: string
    required:
      - data
      - source
      - type

  Events:
    type: object
    properties:
      nextPageKey:
        type: string
        description: Pointer to next page, base64 encoded
      totalCount:
        type: number
        description: Total number of resources
      pageSize:
        type: number
        description: Size of returned page
      events:
        type: array
        items:
          $ref: '#/definitions/KeptnContextExtendedCE'

# dummy path that is required by go-swagger
paths:
  '/dummy':
    get:
      responses:
        '200':
          description: Success
