
name: reviewdog
on: [pull_request]
env:
  GO_VERSION: 1.18
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Check out code.
        uses: actions/checkout@v3

      - name: golangci-lint-action
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2

      - name: reviewdog-action
        uses: reviewdog/action-golangci-lint@v2.1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_version: ${{ env.GO_VERSION }}
          fail_on_error: true
          reporter: github-pr-check
