
name: reviewdog
on: [pull_request]
env:
  GO_VERSION: "1.20"
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Check out code.
        uses: actions/checkout@v3

      - name: reviewdog-action
        uses: reviewdog/action-golangci-lint@v2.3.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_version: ${{ env.GO_VERSION }}
          fail_on_error: true
          reporter: github-pr-review
          golangci_lint_flags: --timeout 3m
