
name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--disable-all -E deadcode,errcheck,gosimple,govet,ineffassign,staticcheck,typecheck,unused,funlen,dupl"
          github_token: ${{ secrets.GITHUB_TOKEN }}
